//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_STUDENTS.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Term
    {
        public Term()
        {
            this.Grade = new HashSet<Grade>();
        }
    
        public int TermId { get; set; }
        public string TermName { get; set; }
    
        public virtual ICollection<Grade> Grade { get; set; }
    }
}
